version: 0.2

phases:
  build:
    commands:
      - echo "Deploying frontend...."

      - |
        aws ssm send-command \
        --instance-ids i-00c9c1576a9b26183 \
        --document-name "AWS-RunShellScript" \
        --parameters '{
          "commands":[
            "cd /opt/noah-frontend",
            "git pull origin qa",
            "cd /opt/noah",
            "docker compose up -d --build frontend"
          ]
        }'
